-- MySQL Script generated by MySQL Workbench
-- Sun Jul  8 13:39:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Alquila_Auto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Alquila_Auto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Alquila_Auto` DEFAULT CHARACTER SET utf8 ;
USE `Alquila_Auto` ;

-- -----------------------------------------------------
-- Table `Alquila_Auto`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquila_Auto`.`Cliente` (
  `rut` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquila_Auto`.`Oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquila_Auto`.`Oficina` (
  `id_oficina` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(7) NOT NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_oficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquila_Auto`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquila_Auto`.`Vehiculo` (
  `patente` VARCHAR(7) NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `fk_oficina` INT NOT NULL,
  PRIMARY KEY (`patente`),
  INDEX `fk_oficina_idx` (`fk_oficina` ASC),
  CONSTRAINT `fk_oficina`
    FOREIGN KEY (`fk_oficina`)
    REFERENCES `Alquila_Auto`.`Oficina` (`id_oficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquila_Auto`.`Alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquila_Auto`.`Alquiler` (
  `id_alquiler` INT NOT NULL AUTO_INCREMENT,
  `fk_rut` VARCHAR(13) NOT NULL,
  `fk_patente` VARCHAR(7) NOT NULL,
  `precio` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_alquiler`),
  INDEX `fk_rut_idx` (`fk_rut` ASC),
  INDEX `fk_patente_idx` (`fk_patente` ASC),
  CONSTRAINT `fk_rut`
    FOREIGN KEY (`fk_rut`)
    REFERENCES `Alquila_Auto`.`Cliente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patente`
    FOREIGN KEY (`fk_patente`)
    REFERENCES `Alquila_Auto`.`Vehiculo` (`patente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
